apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{  .Chart.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: "{{  .Chart.Name }}-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector: 
    matchLabels:
      app: "{{  .Chart.Name }}"
      version: "current"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}"
        version: "current"
    spec:
      containers:
      - env:
        - name: ASSISTANT_AUTH_TYPE
          value : "{{ .Values.services.assistant.authtype }}"
        - name: ASSISTANT_APIKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.assistant.secretKeyRef}}
              key: apikey
              optional: true
        - name: ASSISTANT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.assistant.secretKeyRef}}
              key: url
              optional: true
        - name: DISCOVERY_AUTH_TYPE
          value : "{{ .Values.services.discovery.authtype }}"
        - name: DISCOVERY_APIKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.discovery.secretKeyRef}}
              key: apikey
              optional: true
        - name: DISCOVERY_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.discovery.secretKeyRef}}
              key: url
              optional: true
        - name: NATURAL_LANGUAGE_UNDERSTANDING_AUTH_TYPE
          value : "{{ .Values.services.nlu.authtype }}"
        - name: NATURAL_LANGUAGE_UNDERSTANDING_APIKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.nlu.secretKeyRef}}
              key: apikey
              optional: true
        - name: NATURAL_LANGUAGE_UNDERSTANDING_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.nlu.secretKeyRef}}
              key: url
              optional: true
        - name: PORT
          value : "{{ .Values.service.servicePort }}"
        - name: APPLICATION_NAME
          value: "{{ .Release.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.servicePort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
        name: "{{  .Chart.Name  }}"
        ports:
        - containerPort: {{ .Values.service.servicePort}}
          protocol: TCP
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
