apiVersion: apps/v1
kind: Deployment
metadata:
 ...
spec:
 ...
  template:
    ...
    spec:
      containers:
        env:
        - name: ASSISTANT_AUTH_TYPE
          value : "{{ .Values.services.assistant.authtype }}"
        -name: ASSISTANT_APIKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.assistant.secretKeyRef}}
              key: apikey
              optional: true
        -name: ASSISTANT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.assistant.secretKeyRef}}
              key: url
              optional: true
        - name: PORT
          value : "{{ .Values.service.servicePort }}"
        - name: APPLICATION_NAME
          value: "{{ .Release.Name }}"
          